"use client";

import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Download, RefreshCw } from "lucide-react";
import { trafficSeries } from "@/data/operational-mock-data";
import { ContextSidebar, EnterpriseButton, FilterToolbar, MetricCard, OperationalPageHeader, Panel, StatusBadge } from "@/components/operational/enterprise-ui";

export function OperationsReport() {
  return <div className="-m-6 flex min-h-[calc(100dvh-52px)] md:-m-6 lg:-m-8"><div className="hidden lg:block"><ContextSidebar active="Operações" /></div><div className="min-w-0 flex-1 p-6 lg:p-8"><OperationalPageHeader eyebrow="Analytics / Operações" title="Desempenho operacional" description="01 de julho de 2026 - 21 de julho de 2026" actions={<><EnterpriseButton><RefreshCw aria-hidden/> Atualizar</EnterpriseButton><EnterpriseButton variant="primary"><Download aria-hidden/> Baixar PDF</EnterpriseButton></>}/><FilterToolbar/><div className="mt-6 enterprise-grid"><MetricCard label="Total de operações" value="14.814" delta="Período selecionado" tone="neutral"/><MetricCard label="Concluídas" value="14.505" delta="97,9% de sucesso"/><MetricCard label="Pendências" value="309" delta="2,1% das operações" tone="danger"/><MetricCard label="Dados processados" value="2,8 GB" delta="+12% no período" tone="neutral"/><MetricCard label="Tempo médio" value="2m 18s" delta="-12s em relação ao período"/><MetricCard label="Disponibilidade" value="99,98%" delta="Dentro da meta operacional"/></div><div className="mt-6 enterprise-grid"><Panel title="Operações por dia" className="col-span-12"><div className="h-[360px] p-4"><ResponsiveContainer width="100%" height="100%"><BarChart data={trafficSeries} margin={{ top: 16, right: 12, left: 0, bottom: 0 }}><CartesianGrid stroke="#e0e0e0" vertical={false}/><XAxis dataKey="label" tick={{ fontSize: 12, fill: "#6f6f6f" }} axisLine={{ stroke: "#c6c6c6" }} tickLine={false}/><YAxis tick={{ fontSize: 12, fill: "#6f6f6f" }} axisLine={false} tickLine={false}/><Tooltip contentStyle={{ background: "#fff", border: "1px solid #c6c6c6", borderRadius: 2, fontSize: 12 }}/><Legend wrapperStyle={{ fontSize: 12 }}/><Bar dataKey="sucesso" name="Concluídas" fill="#24a148"/><Bar dataKey="erros" name="Pendências" fill="#da1e28"/></BarChart></ResponsiveContainer></div></Panel><Panel title="Operações com maior impacto" className="col-span-12"><div className="overflow-x-auto"><table className="enterprise-table"><thead><tr><th>Fluxo</th><th>Operações</th><th>Taxa de sucesso</th><th>Tempo médio</th><th>Status</th></tr></thead><tbody>{[["Simulação residencial","4.892","99,3%","1m 54s","Online"],["Cadastro de cliente","3.118","98,8%","2m 11s","Online"],["Importação de produtos","1.746","94,2%","4m 42s","Atenção"],["Revisão de documentos","976","97,1%","3m 06s","Online"]].map((item) => <tr key={item[0]}><td>{item[0]}</td><td>{item[1]}</td><td>{item[2]}</td><td>{item[3]}</td><td><StatusBadge status={item[4]}/></td></tr>)}</tbody></table></div></Panel></div></div></div>;
}
