"use client";

import { useMemo, useState } from "react";
import { Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis, CartesianGrid, Bar, BarChart } from "recharts";
import { Plus } from "lucide-react";
import Link from "next/link";
import { channelVolume, distribution, operationalResources, trafficSeries } from "@/data/operational-mock-data";
import { EnterpriseButton, FilterToolbar, MetricCard, OperationalPageHeader, Panel, StatusBadge } from "@/components/operational/enterprise-ui";

const chartTooltip = { background: "#fff", border: "1px solid #c6c6c6", borderRadius: 2, fontSize: 12 };

export function OperationsDashboard() {
  const [refreshedAt, setRefreshedAt] = useState("Atualizado há 4 minutos");
  const [status, setStatus] = useState("Todos");
  const resources = useMemo(() => status === "Todos" ? operationalResources : operationalResources.filter((item) => item.status === status), [status]);
  return <div className="space-y-6">
    <OperationalPageHeader title="Visão geral" actions={<><EnterpriseButton nativeButton={false} render={<Link href="/atendimento" />} variant="primary"><Plus aria-hidden /> Novo atendimento</EnterpriseButton></>} />
    <div className="enterprise-tabs" role="tablist" aria-label="Módulos"><button className="enterprise-tab enterprise-tab-active" role="tab" aria-selected>Visão geral</button><button className="enterprise-tab" role="tab">Atendimento</button><button className="enterprise-tab" role="tab">Simulações</button><button className="enterprise-tab" role="tab">Produtos</button><button className="enterprise-tab" role="tab">Equipe</button></div>
    <FilterToolbar onRefresh={() => setRefreshedAt("Atualizado agora")} lastUpdated={refreshedAt} />
    <div className="enterprise-grid"><MetricCard label="Operações no período" value="14.814" delta="+8,4% em relação ao período anterior" /><MetricCard label="Clientes ativos" value="1.247" delta="+5,2% no período" /><MetricCard label="Taxa de sucesso" value="98,1%" delta="+0,6 p.p. no período" /><MetricCard label="Pendências" value="32" delta="6 críticas exigem revisão" tone="danger" /><MetricCard label="Produtos ativos" value="151" delta="+7 publicações recentes" /><MetricCard label="Tempo médio" value="2m 18s" delta="-12s em relação ao período anterior" /></div>
    <div className="enterprise-grid">
      <Panel title="Volume de operações" className="col-span-12 xl:col-span-8"><div className="h-[310px] p-4"><ResponsiveContainer width="100%" height="100%"><LineChart data={trafficSeries} margin={{ top: 10, right: 12, left: -12, bottom: 0 }}><CartesianGrid stroke="#e0e0e0" vertical={false}/><XAxis dataKey="label" tick={{ fill: "#6f6f6f", fontSize: 12 }} axisLine={{ stroke: "#c6c6c6" }} tickLine={false}/><YAxis tick={{ fill: "#6f6f6f", fontSize: 12 }} axisLine={false} tickLine={false}/><Tooltip contentStyle={chartTooltip}/><Legend wrapperStyle={{ fontSize: 12 }}/><Line type="linear" dataKey="sucesso" name="Concluídas" stroke="#4589ff" strokeWidth={2} dot={false}/><Line type="linear" dataKey="erros" name="Com pendência" stroke="#da1e28" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div></Panel>
      <Panel title="Distribuição de operações" className="col-span-12 xl:col-span-4"><div className="relative h-[310px] p-4"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={distribution} dataKey="value" nameKey="name" innerRadius={64} outerRadius={92} paddingAngle={1} stroke="none">{distribution.map((entry) => <Cell key={entry.name} fill={entry.color}/>)}</Pie><Tooltip contentStyle={chartTooltip}/><Legend verticalAlign="bottom" iconType="square" wrapperStyle={{ fontSize: 12 }}/></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center pb-10"><strong className="text-3xl font-normal">14.814</strong><span className="text-xs text-[#6f6f6f]">operações</span></div></div></Panel>
      <Panel title="Volume por fluxo" className="col-span-12 lg:col-span-5"><div className="h-[280px] p-4"><ResponsiveContainer width="100%" height="100%"><BarChart layout="vertical" data={channelVolume} margin={{ top: 4, right: 18, left: 50, bottom: 0 }}><CartesianGrid stroke="#e0e0e0" horizontal={false}/><XAxis type="number" tick={{ fill: "#6f6f6f", fontSize: 12 }} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="name" width={120} tick={{ fill: "#525252", fontSize: 12 }} axisLine={false} tickLine={false}/><Tooltip contentStyle={chartTooltip}/><Bar dataKey="volume" name="Operações" fill="#4589ff" radius={0}/></BarChart></ResponsiveContainer></div></Panel>
      <Panel title="Eventos recentes" className="col-span-12 lg:col-span-7"><div className="divide-y divide-[#e0e0e0]">{["Produto residencial publicado para a equipe comercial", "Importação de tabela requer revisão dos valores", "Indicadores financeiros sincronizados com sucesso", "Nova simulação compartilhada com o cliente"].map((event, index) => <div key={event} className="flex items-center justify-between gap-4 px-4 py-4"><div><p className="text-sm text-[#161616]">{event}</p><p className="mt-1 text-xs text-[#6f6f6f]">{index + 1} hora{index ? "s" : ""} atrás</p></div><StatusBadge status={index === 1 ? "Atenção" : "Ativo"}/></div>)}</div></Panel>
      <Panel title="Atividade operacional" className="col-span-12" action={<label className="text-xs text-[#525252]">Status <select value={status} onChange={(event) => setStatus(event.target.value)} className="ml-2 h-8 border border-[#c6c6c6] bg-white px-2 text-[#161616]"><option>Todos</option><option>Ativo</option><option>Atenção</option><option>Pendente</option></select></label>}><div className="overflow-x-auto"><table className="enterprise-table"><thead><tr><th>ID</th><th>Recurso</th><th>Responsável</th><th>Atualização</th><th>Status</th></tr></thead><tbody>{resources.map((item) => <tr key={item.id}><td className="font-mono text-xs text-[#525252]">{item.id}</td><td>{item.recurso}</td><td>{item.responsavel}</td><td className="text-[#525252]">{item.atualizado}</td><td><StatusBadge status={item.status}/></td></tr>)}{resources.length === 0 && <tr><td colSpan={5} className="text-center text-[#6f6f6f]">Nenhum registro encontrado para os filtros selecionados.</td></tr>}</tbody></table></div></Panel>
    </div>
  </div>;
}
